local LSM = LibStub("LibSharedMedia-3.0") 

-- ----- 
-- BACKGROUND 
-- ----- 
LSM:Register("background", "action2", [[Interface\Addons\SharedMedia_MyMedia\background\action2.tga]]) 
LSM:Register("background", "action3", [[Interface\Addons\SharedMedia_MyMedia\background\action3.tga]]) 
LSM:Register("background", "bar", [[Interface\Addons\SharedMedia_MyMedia\background\bar.tga]]) 
LSM:Register("background", "editpolish", [[Interface\Addons\SharedMedia_MyMedia\background\editpolish.tga]]) 
LSM:Register("background", "Overlayrect", [[Interface\Addons\SharedMedia_MyMedia\background\Overlayrect.tga]]) 
LSM:Register("background", "rectshadow", [[Interface\Addons\SharedMedia_MyMedia\background\rectshadow.tga]]) 
LSM:Register("background", "screenoverlay", [[Interface\Addons\SharedMedia_MyMedia\background\screenoverlay.tga]]) 
LSM:Register("background", "shadow square", [[Interface\Addons\SharedMedia_MyMedia\background\shadow square.tga]]) 

-- ----- 
--  BORDER 
-- ---- 
LSM:Register("border", "AceGUI-3.0-SharedMediaWidgets", [[Interface\Addons\SharedMedia_MyMedia\border\AceGUI-3.0-SharedMediaWidgets.toc]]) 
LSM:Register("border", "adapt", [[Interface\Addons\SharedMedia_MyMedia\border\adapt.blp]]) 
LSM:Register("border", "Armory", [[Interface\Addons\SharedMedia_MyMedia\border\Armory.tga]]) 
LSM:Register("border", "arrow", [[Interface\Addons\SharedMedia_MyMedia\border\arrow.tga]]) 
LSM:Register("border", "BorderWidget", [[Interface\Addons\SharedMedia_MyMedia\border\BorderWidget.lua]]) 
LSM:Register("border", "border_1", [[Interface\Addons\SharedMedia_MyMedia\border\border_1.tga]]) 
LSM:Register("border", "border_2", [[Interface\Addons\SharedMedia_MyMedia\border\border_2.tga]]) 
LSM:Register("border", "border_3", [[Interface\Addons\SharedMedia_MyMedia\border\border_3.tga]]) 
LSM:Register("border", "bubbleTex", [[Interface\Addons\SharedMedia_MyMedia\border\bubbleTex.tga]]) 
LSM:Register("border", "Chat_RPG", [[Interface\Addons\SharedMedia_MyMedia\border\Chat_RPG.blp]]) 
LSM:Register("border", "combo", [[Interface\Addons\SharedMedia_MyMedia\border\combo.tga]]) 
LSM:Register("border", "copy", [[Interface\Addons\SharedMedia_MyMedia\border\copy.tga]]) 
LSM:Register("border", "cross", [[Interface\Addons\SharedMedia_MyMedia\border\cross.tga]]) 
LSM:Register("border", "dps", [[Interface\Addons\SharedMedia_MyMedia\border\dps.tga]]) 
LSM:Register("border", "Empty", [[Interface\Addons\SharedMedia_MyMedia\border\Empty.tga]]) 
LSM:Register("border", "Falumn", [[Interface\Addons\SharedMedia_MyMedia\border\Falumn.tga]]) 
LSM:Register("border", "fer1", [[Interface\Addons\SharedMedia_MyMedia\border\fer1.tga]]) 
LSM:Register("border", "fer10", [[Interface\Addons\SharedMedia_MyMedia\border\fer10.tga]]) 
LSM:Register("border", "fer11", [[Interface\Addons\SharedMedia_MyMedia\border\fer11.tga]]) 
LSM:Register("border", "fer14", [[Interface\Addons\SharedMedia_MyMedia\border\fer14.tga]]) 
LSM:Register("border", "fer16", [[Interface\Addons\SharedMedia_MyMedia\border\fer16.tga]]) 
LSM:Register("border", "fer17", [[Interface\Addons\SharedMedia_MyMedia\border\fer17.tga]]) 
LSM:Register("border", "fer2", [[Interface\Addons\SharedMedia_MyMedia\border\fer2.tga]]) 
LSM:Register("border", "fer24", [[Interface\Addons\SharedMedia_MyMedia\border\fer24.tga]]) 
LSM:Register("border", "fer26", [[Interface\Addons\SharedMedia_MyMedia\border\fer26.tga]]) 
LSM:Register("border", "fer3", [[Interface\Addons\SharedMedia_MyMedia\border\fer3.tga]]) 
LSM:Register("border", "fer35", [[Interface\Addons\SharedMedia_MyMedia\border\fer35.tga]]) 
LSM:Register("border", "fer36", [[Interface\Addons\SharedMedia_MyMedia\border\fer36.tga]]) 
LSM:Register("border", "fer37", [[Interface\Addons\SharedMedia_MyMedia\border\fer37.tga]]) 
LSM:Register("border", "fer4", [[Interface\Addons\SharedMedia_MyMedia\border\fer4.tga]]) 
LSM:Register("border", "fer5", [[Interface\Addons\SharedMedia_MyMedia\border\fer5.tga]]) 
LSM:Register("border", "fer6", [[Interface\Addons\SharedMedia_MyMedia\border\fer6.tga]]) 
LSM:Register("border", "fer7", [[Interface\Addons\SharedMedia_MyMedia\border\fer7.tga]]) 
LSM:Register("border", "fer8", [[Interface\Addons\SharedMedia_MyMedia\border\fer8.tga]]) 
LSM:Register("border", "Flat", [[Interface\Addons\SharedMedia_MyMedia\border\Flat.tga]]) 
LSM:Register("border", "healer", [[Interface\Addons\SharedMedia_MyMedia\border\healer.tga]]) 
LSM:Register("border", "mail", [[Interface\Addons\SharedMedia_MyMedia\border\mail.tga]]) 
LSM:Register("border", "Minimalist", [[Interface\Addons\SharedMedia_MyMedia\border\Minimalist.tga]]) 
LSM:Register("border", "outfitter", [[Interface\Addons\SharedMedia_MyMedia\border\outfitter.blp]]) 
LSM:Register("border", "Outline", [[Interface\Addons\SharedMedia_MyMedia\border\Outline.tga]]) 
LSM:Register("border", "pause", [[Interface\Addons\SharedMedia_MyMedia\border\pause.blp]]) 
LSM:Register("border", "Perl", [[Interface\Addons\SharedMedia_MyMedia\border\Perl.tga]]) 
LSM:Register("border", "pHempty", [[Interface\Addons\SharedMedia_MyMedia\border\pHempty.tga]]) 
LSM:Register("border", "play", [[Interface\Addons\SharedMedia_MyMedia\border\play.blp]]) 
LSM:Register("border", "reset", [[Interface\Addons\SharedMedia_MyMedia\border\reset.blp]]) 
LSM:Register("border", "SLE_Chat_Logo", [[Interface\Addons\SharedMedia_MyMedia\border\SLE_Chat_Logo.blp]]) 
LSM:Register("border", "SLE_Chat_LogoD", [[Interface\Addons\SharedMedia_MyMedia\border\SLE_Chat_LogoD.blp]]) 
LSM:Register("border", "tank", [[Interface\Addons\SharedMedia_MyMedia\border\tank.tga]]) 
LSM:Register("border", "widget", [[Interface\Addons\SharedMedia_MyMedia\border\widget.xml]]) 

-- -----
--   FONT
-- -----
LSM:Register("font", "Action_Man", [[Interface\Addons\SharedMedia_MyMedia\font\Action_Man.ttf]]) 
LSM:Register("font", "Adventure", [[Interface\Addons\SharedMedia_MyMedia\font\Adventure.ttf]]) 
LSM:Register("font", "Bazooka", [[Interface\Addons\SharedMedia_MyMedia\font\Bazooka.ttf]]) 
LSM:Register("font", "BlackChancery", [[Interface\Addons\SharedMedia_MyMedia\font\BlackChancery.ttf]]) 
LSM:Register("font", "CelestiaMediumRedux1.55", [[Interface\Addons\SharedMedia_MyMedia\font\CelestiaMediumRedux1.55.ttf]]) 
LSM:Register("font", "Continuum_Medium", [[Interface\Addons\SharedMedia_MyMedia\font\Continuum_Medium.ttf]]) 
LSM:Register("font", "DieDieDie", [[Interface\Addons\SharedMedia_MyMedia\font\DieDieDie.ttf]]) 
LSM:Register("font", "Expressway", [[Interface\Addons\SharedMedia_MyMedia\font\Expressway.ttf]]) 
LSM:Register("font", "Homespun", [[Interface\Addons\SharedMedia_MyMedia\font\Homespun.ttf]]) 
LSM:Register("font", "HookedUp", [[Interface\Addons\SharedMedia_MyMedia\font\HookedUp.ttf]]) 
LSM:Register("font", "Invisible", [[Interface\Addons\SharedMedia_MyMedia\font\Invisible.ttf]]) 
LSM:Register("font", "PT_Sans_Narrow", [[Interface\Addons\SharedMedia_MyMedia\font\PT_Sans_Narrow.ttf]]) 

-- -----
--   SOUND
-- -----
LSM:Register("sound", "announcementonawharf", [[Interface\Addons\SharedMedia_MyMedia\sound\announcementonawharf.ogg]]) 
LSM:Register("sound", "awwcrap", [[Interface\Addons\SharedMedia_MyMedia\sound\awwcrap.ogg]]) 
LSM:Register("sound", "bbqass", [[Interface\Addons\SharedMedia_MyMedia\sound\bbqass.ogg]]) 
LSM:Register("sound", "Bloodlust", [[Interface\Addons\SharedMedia_MyMedia\sound\Bloodlust.ogg]]) 
LSM:Register("sound", "coin_dropped_on_wooden_floor", [[Interface\Addons\SharedMedia_MyMedia\sound\coin_dropped_on_wooden_floor.ogg]]) 
LSM:Register("sound", "Computer_Start-Up-Your_Mom-1280862923", [[Interface\Addons\SharedMedia_MyMedia\sound\Computer_Start-Up-Your_Mom-1280862923.ogg]]) 
LSM:Register("sound", "Cuckoo Clock-SoundBible.com-1776874523", [[Interface\Addons\SharedMedia_MyMedia\sound\Cuckoo Clock-SoundBible.com-1776874523.ogg]]) 
LSM:Register("sound", "Ding1", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding1.ogg]]) 
LSM:Register("sound", "Ding2", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding2.ogg]]) 
LSM:Register("sound", "Ding3", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding3.ogg]]) 
LSM:Register("sound", "Ding4", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding4.ogg]]) 
LSM:Register("sound", "Ding5", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding5.ogg]]) 
LSM:Register("sound", "Ding6", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding6.ogg]]) 
LSM:Register("sound", "Ding7", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding7.ogg]]) 
LSM:Register("sound", "Ding8", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding8.ogg]]) 
LSM:Register("sound", "Ding9", [[Interface\Addons\SharedMedia_MyMedia\sound\Ding9.ogg]]) 
LSM:Register("sound", "dumbshit", [[Interface\Addons\SharedMedia_MyMedia\sound\dumbshit.ogg]]) 
LSM:Register("sound", "Electrical_Sweep-Sweeper-1760111493", [[Interface\Addons\SharedMedia_MyMedia\sound\Electrical_Sweep-Sweeper-1760111493.ogg]]) 
LSM:Register("sound", "harlemshake", [[Interface\Addons\SharedMedia_MyMedia\sound\harlemshake.ogg]]) 
LSM:Register("sound", "helloKitty", [[Interface\Addons\SharedMedia_MyMedia\sound\helloKitty.ogg]]) 
LSM:Register("sound", "mamaweekends", [[Interface\Addons\SharedMedia_MyMedia\sound\mamaweekends.ogg]]) 
LSM:Register("sound", "Music_Box-Big_Daddy-1389738694", [[Interface\Addons\SharedMedia_MyMedia\sound\Music_Box-Big_Daddy-1389738694.ogg]]) 
LSM:Register("sound", "Pling1", [[Interface\Addons\SharedMedia_MyMedia\sound\Pling1.ogg]]) 
LSM:Register("sound", "Pling2", [[Interface\Addons\SharedMedia_MyMedia\sound\Pling2.ogg]]) 
LSM:Register("sound", "Pling3", [[Interface\Addons\SharedMedia_MyMedia\sound\Pling3.ogg]]) 
LSM:Register("sound", "Pling4", [[Interface\Addons\SharedMedia_MyMedia\sound\Pling4.ogg]]) 
LSM:Register("sound", "Pling5", [[Interface\Addons\SharedMedia_MyMedia\sound\Pling5.ogg]]) 
LSM:Register("sound", "Pling6", [[Interface\Addons\SharedMedia_MyMedia\sound\Pling6.ogg]]) 
LSM:Register("sound", "runfast", [[Interface\Addons\SharedMedia_MyMedia\sound\runfast.ogg]]) 
LSM:Register("sound", "sheep", [[Interface\Addons\SharedMedia_MyMedia\sound\sheep.mp3]]) 
LSM:Register("sound", "stoprunningslimball", [[Interface\Addons\SharedMedia_MyMedia\sound\stoprunningslimball.ogg]]) 
LSM:Register("sound", "TheGrCorpus", [[Interface\Addons\SharedMedia_MyMedia\sound\TheGrCorpus.mp3]]) 
LSM:Register("sound", "warning", [[Interface\Addons\SharedMedia_MyMedia\sound\warning.ogg]]) 
LSM:Register("sound", "whisper", [[Interface\Addons\SharedMedia_MyMedia\sound\whisper.ogg]]) 
LSM:Register("sound", "yankiebangbang", [[Interface\Addons\SharedMedia_MyMedia\sound\yankiebangbang.ogg]]) 
LSM:Register("sound", "_license", [[Interface\Addons\SharedMedia_MyMedia\sound\_license.txt]]) 

-- -----
--   STATUSBAR
-- -----
LSM:Register("statusbar", "Aluminium", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Aluminium.tga]]) 
LSM:Register("statusbar", "Armory", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Armory.tga]]) 
LSM:Register("statusbar", "arrow", [[Interface\Addons\SharedMedia_MyMedia\statusbar\arrow.tga]]) 
LSM:Register("statusbar", "combo", [[Interface\Addons\SharedMedia_MyMedia\statusbar\combo.tga]]) 
LSM:Register("statusbar", "copy", [[Interface\Addons\SharedMedia_MyMedia\statusbar\copy.tga]]) 
LSM:Register("statusbar", "cross", [[Interface\Addons\SharedMedia_MyMedia\statusbar\cross.tga]]) 
LSM:Register("statusbar", "dps", [[Interface\Addons\SharedMedia_MyMedia\statusbar\dps.tga]]) 
LSM:Register("statusbar", "Empty", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Empty.tga]]) 
LSM:Register("statusbar", "Falumn", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Falumn.tga]]) 
LSM:Register("statusbar", "Fifths", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Fifths.tga]]) 
LSM:Register("statusbar", "Flat", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Flat.tga]]) 
LSM:Register("statusbar", "Fourths", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Fourths.tga]]) 
LSM:Register("statusbar", "Gloss", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Gloss.tga]]) 
LSM:Register("statusbar", "Graphite", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Graphite.tga]]) 
LSM:Register("statusbar", "Grid", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Grid.tga]]) 
LSM:Register("statusbar", "HalA", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalA.tga]]) 
LSM:Register("statusbar", "HalB", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalB.tga]]) 
LSM:Register("statusbar", "HalBorder", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalBorder.tga]]) 
LSM:Register("statusbar", "HalBorderWOTLK", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalBorderWOTLK.tga]]) 
LSM:Register("statusbar", "HalC", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalC.tga]]) 
LSM:Register("statusbar", "HalD", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalD.tga]]) 
LSM:Register("statusbar", "HalE", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalE.tga]]) 
LSM:Register("statusbar", "HalF", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalF.tga]]) 
LSM:Register("statusbar", "HalG", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalG.tga]]) 
LSM:Register("statusbar", "HalH", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalH.tga]]) 
LSM:Register("statusbar", "HalI", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalI.tga]]) 
LSM:Register("statusbar", "HalJ", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalJ.tga]]) 
LSM:Register("statusbar", "HalK", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalK.tga]]) 
LSM:Register("statusbar", "HalL", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalL.tga]]) 
LSM:Register("statusbar", "HalM", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalM.tga]]) 
LSM:Register("statusbar", "HalN", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalN.tga]]) 
LSM:Register("statusbar", "HalO", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalO.tga]]) 
LSM:Register("statusbar", "HalP", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalP.tga]]) 
LSM:Register("statusbar", "HalQ", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalQ.tga]]) 
LSM:Register("statusbar", "HalR", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalR.tga]]) 
LSM:Register("statusbar", "HalS", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalS.tga]]) 
LSM:Register("statusbar", "HalT", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalT.tga]]) 
LSM:Register("statusbar", "HalU", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalU.tga]]) 
LSM:Register("statusbar", "HalV", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalV.tga]]) 
LSM:Register("statusbar", "HalW", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalW.tga]]) 
LSM:Register("statusbar", "HalX", [[Interface\Addons\SharedMedia_MyMedia\statusbar\HalX.tga]]) 
LSM:Register("statusbar", "Melli", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Melli.tga]]) 
LSM:Register("statusbar", "Minimalist", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Minimalist.tga]]) 
LSM:Register("statusbar", "normTex", [[Interface\Addons\SharedMedia_MyMedia\statusbar\normTex.tga]]) 
LSM:Register("statusbar", "normTex2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\normTex2.tga]]) 
LSM:Register("statusbar", "Otravi", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Otravi.tga]]) 
LSM:Register("statusbar", "Outline", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Outline.tga]]) 
LSM:Register("statusbar", "Perl", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Perl.tga]]) 
LSM:Register("statusbar", "Perl2", [[Interface\Addons\SharedMedia_MyMedia\statusbar\Perl2.tga]]) 
